### ISSUE TITLE
Why rename to CamelCase?

### ISSUE THREAD

**Issue by mversic** [pacman82/odbc-sys#29]
I see there was some work being done here. I like that enums were replaced by newtype + consts

I see that some of the structs and types were shortened and/or renamed to CamelCase. One may find that to be more aesthetically pleasing but I think it introduces unnecessary mental switch. If a user consults the ODBC standard, they will have a problem of finding the equivalent identifier(i.e. struct or type name) in this library because it's been shortened or CamelCased.

If this library aims to be a port of the ODBC standard to Rust I maintain that it should not deviate in it's naming conventions. Naming conventions are a part of the standard and if a standard defines names of identifiers then those names should be exposed to users of this library.

Higher level wrappers of this library have not yet caught up with API changes of this library so revert will still be painless if it's decided upon

**Comment by pacman82** [comment]
I am happy you like the newtypes. I am currently still undecided wether to turn the `CDataType` into a newtype, too.

Since the switch to the newtypes, requires some mechanical refactoring anyway I decided to bundle it in with the renaming. In retrospect, seeing that upstream adaption apart from the new `odbc-api` crate is slow, that may have been a mistake and two smaller increments would have been better.

As to your original question of why. It is simply an effort to stick with the Rust naming convention and be idiomatic. The key here is, that deducing the name in the standard should be easy enough.

> Naming conventions are a part of the standard and if a standard defines names of identifiers then those names should be exposed to users of this library.

How do you feel about exposing the original ODBC names in the comments? This way we could give rusty names, yet make the Constants and enum variants easily searchable in the documentation of the C-Library.

**Comment by mversic** [comment]
I understand that you renamed structs/types to CamleCase because that is a Rust convention. The point of my question was to provoke more thorough consideration. IMHO, using CamelCase here is an example of fetishization of rules because enforcement of this convention produces negative net value for a developer and readability of codebase; it forces an unnecessary mental switch from the standardized API to Rust conventions used in this library. I presented an alternative opinion, but it could just be a matter of taste.

If you disagree with my comment then original ODBC names should be exposed in comments as you suggested.

**Comment by pacman82** [comment]
Hello @mversic,

it is a matter of taste and style. In this regarde ours seem to differ. Despite that I thank you for your insight. I'll close the issue and from now on then I perform edits in the library or review PRs I'll mention the original name in the comments and might even paste a link there to the reference for good measure. Any PRs doing this are also welcome, of course.
